### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by karlhorky**
Hey Flavio! Thanks for all of your contributions to the education and documentation on web topics! They are very useful for both beginners and more experienced developers!

Just a quick PR to fix two typos.

### CODE REVIEW

**Comment by flaviocopes** [comment]
Thanks Karl! 

Good catch on the JavScript typo. 

I think "rather than" is correct, though! I just checked on Google, seems so. Do you agree?

**Comment by karlhorky** [comment]
🤦‍♂️ Oh man, yeah, sorry about that! Not sure how I made that mistake.

Unfixed the non-typo hehe

**Comment by flaviocopes** [comment]
Thanks!

**Comment by karlhorky** [comment]
No problem, thanks for the merge!

**Pull request merged**
